name          'example42-heat'
version       '3.0.0.beta3'
source        'https://github.com/example42/puppet-heat'
author        'example42'
license       'Apache License, Version 2.0'
summary       'This module installs and manages heat'
description   'This module installs and manages heat and its services'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
